sudo: required
services:
  - docker

before_install:
  - docker build -t godlzr/docker-react -f Dockerfile.dev .

script:
  - docker run godlzr/docker-react npm run test -- --coverage

depoly:
  provider:
  region:
  app: 'docker'
  env: 'Docker-env'
  bucket_name:
  bucket_path:
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
